name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      run: pip install pyproject.toml && python script/summary.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      
