name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2
    - name: Checkout
      uses: actions/checkout@v3
    - run: poetry export -f requirements.txt -o requirements.txt
    - name: Generate index
      run: |
        pip install -r requirements.txt
        python script/summary.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      
