name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Poetry
      run: curl -sSL https://install.python-poetry.org | python3 - && echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate index
      run: poetry run python script/summary.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      
