name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
           echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate index
      run: poetry run python script/summary.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      
